# fly.toml app configuration file generated for friend-zone-bot on 2024-03-15T02:38:26+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'friend-zone-bot'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.http_service]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/"
    port = 3000
    timeout = "10s"
    type = "http"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
